platform: linux

image_resource:
  type: registry-image
  source: { repository: golang }

inputs:
  - name: code

caches:
  - path: gopath/

run:
  path: /bin/sh
  args: ["code/infrastructure/pipelines/ci/build.sh"]
