---
resources:
  - name: code
    type: git
    icon: git
    source:
      uri: git@github.com:bredr/k8s-ci.git
      branch: master
      private_key: ((git.private-repo-key))
      paths: [services/${SERVICE}, infrastructure/pipelines]    

jobs:
- name: build-${SERVICE}
  plan:
  - get: code
    trigger: true
  - task: build
    inputs:
      - name: code
    file: code/infrastructure/pipelines/meta/gobuildtask.yaml
    params:
      SERVICE: ${SERVICE}
