---
resource_types:
  - name: concourse-pipeline
    type: docker-image
    source:
      repository: concourse/concourse-pipeline-resource
resources:
  - name: meta-pipeline
    type: git
    icon: git
    source:
      uri: git@github.com:bredr/k8s-ci.git
      branch: master
      private_key: ((git.private-repo-key))
  - name: pipelines
    type: concourse-pipeline
    source:
      target: http://$LOCAL_IP
      insecure: "true"
      teams:
        - name: main
          username: ((concourse.username))
          password: ((concourse.password))

jobs:
  - name: set-pipeline
    public: true
    plan:
      - get: meta-pipeline
        trigger: true
      - task: generate-pipelines
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: davidbrett88/envsubst, tag: 0.1.0 }
          inputs:
            - name: meta-pipeline
          outputs:
            - name: out
          run:
            path: /bin/sh
            args:
              [
                "meta-pipeline/infrastructure/pipelines/meta/generatePipeline.sh",
              ]
      - put: pipelines
        inputs: [out]
        params:
          pipelines_file: out/generated-pipelines.yaml
